### PR TITLE
use httputil.ReverseProxy to improve proxy functions

### LINKED ISSUE #11: Update metrics-collecting proxy and activator to use httputil.ReverseProxy
This will do a petter job of preserving all request details (headers, for instance) than we currently do today. (We're not very careful about that currently.)

### PR DESCRIPTION
**Pull request by krancour**
Fixes #11

### CODE REVIEW

**Comment by tariq1890** [comment]
The file structure of proxy.go is metrics/proxy/proxy/proxy.go. I think we'd need to address that

**Comment by tariq1890** [comment]
Could be in another PR. Just wanted to highlight that out.

**Comment by krancour** [comment]
> The file structure of proxy.go is metrics/proxy/proxy/proxy.go. I think we'd need to address that

That was deliberate. It definitely looks odd, except when viewed in a broader context:

Here's a branch from the project tree:

```
pkg/metrics
├── proxy
│   ├── injector
│   │   ├── config.go
│   │   ├── deployment_patch.go
│   │   ├── injector.go
│   │   └── pod_patch.go
│   └── proxy
│       ├── config.go
│       ├── proxy.go
│       └── single_port_proxy.go
└── proxy_request_count.go
```

The idea behind the current project layout is that we're broadly separated by areas of concern such as "managing deployments" (both zeroscaler and activated fall under this), managing endpoints (the endpoints controller and endpoints hijacker both fall under this) and, metrics. Under metrics, there are a few constituent concerns, with one being the proxy, which can further be decomposed in the the proxy itself and the proxy injector.

I think the path looks odd when viewed in isolation, but in context, it probably makes more sense.

I'm still open to alternative names for anything/everything if it helps avoid this kind of awkwardness.... but as you said... handled in a different PR.

**Comment by tariq1890** [comment]
@krancour Rebased this branch and approved.

**Pull request merged**
