### PR TITLE
update example to use latest hello-osiris image

### PR DESCRIPTION
**Pull request by tariq1890**
Refer to the https://github.com/tariq1890/hello-osiris/pull/3 for more details.

### CODE REVIEW

**Comment by krancour** [comment]
The image this references looks like it was manually built/pushed. Let's get the hello-osiris pipelines working so that we've taken any potential for human error out of the equation before we merge any more PRs that reference newer versions of the sample app.

**Comment by tariq1890** [comment]
@krancour Thanks for the review. This has been fixed :)

https://circleci.com/gh/tariq1890/hello-osiris/4

https://github.com/tariq1890/hello-osiris/releases

**Comment by krancour** [comment]
@tariq1890 thanks for sorting that out.

**Comment by krancour** [comment]
LGTM

**Pull request merged**
